{
  "props": [],
  "components": {
    "exporter": {
      "type": "script\\FileChooserScript",
      "x": 224,
      "y": 32,
      "props": {
        "saveDialog": true,
        "filterName": "Файлы конфигурации",
        "filterExtensions": "*.ini,*.cfg",
        "filterAny": true,
        "inputNode": "",
        "actionNode": ""
      }
    },
    "ini": {
      "type": "script\\storage\\IniStorage",
      "x": 96,
      "y": 32,
      "props": {
        "path": "",
        "autoSave": "1",
        "multiLineValues": "1"
      }
    },
    "importer": {
      "type": "script\\FileChooserScript",
      "x": 160,
      "y": 32,
      "props": {
        "filterName": "Файлы конфигурации",
        "filterExtensions": "*.ini,*.cfg",
        "filterAny": true,
        "inputNode": "",
        "actionNode": ""
      }
    },
    "request": {
      "type": "script\\TimerScript",
      "x": 32,
      "y": 32,
      "props": {
        "interval": "1000",
        "repeatable": "1",
        "autoStart": false
      }
    }
  }
}